name: GoFmt Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gofmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Run gofmt
        run: |
          go fmt ./...
        continue-on-error: true # フォーマットエラーがあってもジョブを失敗させない
